## Pandas

we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. We covers the topics  in this order:

* Series
* DataFrames
* Missing Data
* GroupBy
* Data Input and Output

In [1]:
#!pip3 install pandas

### Series

Series is a one-dimensional labeled array Which are  capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index.

In [2]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [3]:
import numpy as np
import pandas as pd

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series()

Series([], dtype: float64)

In [7]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

#### NumPy Arrays 

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

### Dictionary

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

##### A pandas Series can hold a variety of object types:

In [3]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

### Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like dictionary).

Let's see some examples of how to grab information from a Series. Let us create two series,series1 and series2:

In [4]:
series1 = pd.Series([1,2,3,4],index = ['Trivandrum', 'Kozhikode','Kannur', 'Ernakulam'])  

In [14]:
series2 = pd.Series([1,2,3,4],index = ['Trivandrum', 'Kozhikode','Kollam', 'Ernakulam'])    

In [15]:
series1 + series2

Ernakulam     8.0
Kannur        NaN
Kollam        NaN
Kozhikode     4.0
Trivandrum    2.0
dtype: float64

# Dataframes
A Data frame is a two-dimensional data structure,Here data is aligned in a tabular format in rows and columns.
Dataframe is a collection of series(columns) are of different types.Size are Mutable

In [10]:
import pandas as pd
import numpy as np

In [11]:
from numpy.random import randn
randn(5,5)

array([[-0.84935028, -1.94542833,  0.36774482, -0.93829443, -1.17073157],
       [-1.24053579,  0.49953939,  0.58800412, -0.55515603, -0.33522059],
       [ 0.27853424, -1.85963221,  0.3378916 , -1.37130782,  0.74018254],
       [ 0.17345933, -1.18998411, -0.52283977, -0.6750173 ,  0.01054433],
       [-0.89789066,  0.88399724, -0.74982741, -0.94069863,  1.28412619]])

In [12]:
from numpy.random import randn
randn(5,4)

array([[-0.20809505,  0.53934211,  1.53061797,  2.44170839],
       [-0.27182758,  0.3539164 ,  1.78570475, -0.48477186],
       [-0.26042339,  0.41801509,  1.92658568, -0.73604011],
       [-0.80030801,  1.80688049,  1.23177072, -1.27046619],
       [-0.34148527,  0.80648669, -1.16441912,  0.16909379]])

In [35]:
df= pd.DataFrame()

In [14]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [15]:
df

W         X         Y         Z
A  0.364721  0.277371 -0.605238  0.157147
B -0.128524 -0.655657 -0.237653 -1.264141
C  1.460266  0.969932  1.123065  0.815531
D -0.989335 -0.838934 -0.243994 -0.304270
E  0.764496  0.490776  0.632876  1.355438

In [16]:
randn(3,5)

array([[-1.15822115,  0.62464549, -1.74635064, -1.24066574,  0.28020168],
       [-1.55129789, -1.07539841, -0.44618234, -0.82087458, -1.05990371],
       [-0.54603787,  0.62384011, -0.81788599,  1.51392146,  0.1979846 ]])

### Selection and Indexing

Let's learn the various approach to grab data from a DataFrame


In [9]:
df['W']

A    0.054430
B   -2.226109
C   -0.521061
D    2.873108
E   -0.484199
Name: W, dtype: float64

In [17]:
# Pass a list of column names
df[['X','Y']]

X         Y
A  0.277371 -0.605238
B -0.655657 -0.237653
C  0.969932  1.123065
D -0.838934 -0.243994
E  0.490776  0.632876

In [18]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    0.364721
B   -0.128524
C    1.460266
D   -0.989335
E    0.764496
Name: W, dtype: float64

In [19]:
type(df['W'])

pandas.core.series.Series

### Creating a new column:


In [20]:
df['result'] =df['W'] +df['Y']

In [21]:
#df['new'] = df['W'] + df['Y']

In [22]:
df

W         X         Y         Z    result
A  0.364721  0.277371 -0.605238  0.157147 -0.240517
B -0.128524 -0.655657 -0.237653 -1.264141 -0.366177
C  1.460266  0.969932  1.123065  0.815531  2.583331
D -0.989335 -0.838934 -0.243994 -0.304270 -1.233329
E  0.764496  0.490776  0.632876  1.355438  1.397372

Removing Columns

In [23]:
df.drop('E',axis=0,inplace=True)

In [24]:
# Not inplace unless specified!
df

W         X         Y         Z    result
A  0.364721  0.277371 -0.605238  0.157147 -0.240517
B -0.128524 -0.655657 -0.237653 -1.264141 -0.366177
C  1.460266  0.969932  1.123065  0.815531  2.583331
D -0.989335 -0.838934 -0.243994 -0.304270 -1.233329

In [26]:
df.drop('result',axis=1,inplace=True)

In [27]:
df

W         X         Y         Z
A  0.364721  0.277371 -0.605238  0.157147
B -0.128524 -0.655657 -0.237653 -1.264141
C  1.460266  0.969932  1.123065  0.815531
D -0.989335 -0.838934 -0.243994 -0.304270

In [28]:
df.drop('D',axis=0)

W         X         Y         Z
A  0.364721  0.277371 -0.605238  0.157147
B -0.128524 -0.655657 -0.237653 -1.264141
C  1.460266  0.969932  1.123065  0.815531

In [29]:
df

W         X         Y         Z
A  0.364721  0.277371 -0.605238  0.157147
B -0.128524 -0.655657 -0.237653 -1.264141
C  1.460266  0.969932  1.123065  0.815531
D -0.989335 -0.838934 -0.243994 -0.304270

Selecting Rows

In [31]:
df.loc['A']

W    0.364721
X    0.277371
Y   -0.605238
Z    0.157147
Name: A, dtype: float64

In [ ]:
df.iloc[0]

### Selecting subset of rows and columns 

In [ ]:
df.loc['B','Y']

In [ ]:
df.loc[['A','B'],['W','Y']]

### Conditional Selection

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df[df['W']>0][['Y','X']]

#### For two conditions you can use | and & with parenthesis:


In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

In [ ]:
df

In [ ]:
df.reset_index()

In [ ]:
newnames = 'a b c d e'.split()
newnames

In [ ]:
df['result'] = newnames

In [ ]:
df

In [ ]:
df.set_index('names')

In [ ]:
df.set_index('names',inplace=True)

In [ ]:
df

# Missing Data

In [32]:
import numpy as np
import pandas as pd

In [33]:
mdata = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [34]:
mdata

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [36]:
mdata.dropna()

A    B  C
0  1.0  5.0  1

In [37]:
mdata.dropna(axis=1)

C
0  1
1  2
2  3

In [42]:
mdata.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C]
Index: []

In [43]:
mdata.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [44]:
mdata['A']

0    1.0
1    2.0
2    NaN
Name: A, dtype: float64

In [45]:
mdata['A'].fillna(value=mdata['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## Groupby

#### The groupby method allows you to group rows of data together and call aggregate functions

In [46]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOGLE','GOOGLE','MICROSOFT','MICROSOFT','FACEBOOK','FACEBOOK'],
       'Person':['Kailas','Sanal','Amy','Sudeesh','Shanid','Jaison'],
       'Sales':[200,120,340,124,243,350]}

In [47]:
df = pd.DataFrame(data)

In [48]:
df

Company   Person  Sales
0     GOOGLE   Kailas    200
1     GOOGLE    Sanal    120
2  MICROSOFT      Amy    340
3  MICROSOFT  Sudeesh    124
4   FACEBOOK   Shanid    243
5   FACEBOOK   Jaison    350

In [49]:
df.groupby('Company')

In [50]:
#You can save this object as a new variable:
by_comp = df.groupby("Company")
by_comp

In [51]:
by_comp.mean()

Sales
Company         
FACEBOOK   296.5
GOOGLE     160.0
MICROSOFT  232.0

In [52]:
#More examples of aggregate methods:
by_comp.std()

Sales
Company              
FACEBOOK    75.660426
GOOGLE      56.568542
MICROSOFT  152.735065

In [53]:
by_comp.min()

Person  Sales
Company                 
FACEBOOK   Jaison    243
GOOGLE     Kailas    120
MICROSOFT     Amy    124

In [ ]:
by_comp.max()

In [54]:
by_comp.count()

Person  Sales
Company                 
FACEBOOK        2      2
GOOGLE          2      2
MICROSOFT       2      2

In [55]:
by_comp.describe()

Sales                                                        
          count   mean         std    min     25%    50%     75%    max
Company                                                                
FACEBOOK    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOGLE      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MICROSOFT   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [56]:
by_comp.describe()

Sales                                                        
          count   mean         std    min     25%    50%     75%    max
Company                                                                
FACEBOOK    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOGLE      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MICROSOFT   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [57]:
by_comp.describe().transpose()['GOOGLE']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOGLE, dtype: float64

### Data Input and Output

In [3]:
import numpy as np
import pandas as pd

### CSV
CSV Input

In [4]:
pwd

'/root/Downloads/ICFOSS ML 1 Course Materials-20200611/Day 2/Pandas'

In [5]:
df = pd.read_csv('/root/Downloads/ICFOSS ML 1 Course Materials-20200611/Day 2/Pandas/mtcars.csv')
df.head(11)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0           Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1       Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2          Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3      Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4   Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5             Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6          Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7           Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8            Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9            Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10          Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4

In [6]:
df = pd.read_csv('mtcars.csv')
#df.head()

In [7]:
#!pip install pandas-profiling

In [8]:
#import pandas_profiling
#pandas_profiling.ProfileReport(df)

In [9]:
# Use the multi-axes indexing funtion
print (df.loc[[10,1],['mpg','cyl']])

     mpg  cyl
10  17.8    6
1   21.0    6


In [10]:
# Use the multi-axes indexing funtion
print (df.loc[2:16,['mpg','cyl']])

     mpg  cyl
2   22.8    4
3   21.4    6
4   18.7    8
5   18.1    6
6   14.3    8
7   24.4    4
8   22.8    4
9   19.2    6
10  17.8    6
11  16.4    8
12  17.3    8
13  15.2    8
14  10.4    8
15  10.4    8
16  14.7    8


## Excel

In [65]:
#!pip install xlrd

In [68]:
import xlrd
xx = pd.read_excel('Sample-Sales-Data.xlsx',sheetname='Sheet1')
print(xx)

TypeError: read_excel() got an unexpected keyword argument `sheetname`

In [ ]:
#!pip install xlrd

In [ ]:
# Use the multi-axes indexing funtion
print (xx.loc[[1,3,5],['Year','Value']])

In [67]:
print (xx[0:5]['Value'])

NameError: name 'xx' is not defined

# HTML

In [ ]:
#!pip install lxml
#!pip install html5lib
#!pip install BeautifulSoup4

## HTML Input

In [20]:
df2 = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [21]:
df2

[                                             Bank Name                City  \
 0                                 The First State Bank       Barboursville   
 1                                   Ericson State Bank             Ericson   
 2                     City National Bank of New Jersey              Newark   
 3                                        Resolute Bank              Maumee   
 4                                Louisa Community Bank              Louisa   
 5                                 The Enloe State Bank              Cooper   
 6                  Washington Federal Bank for Savings             Chicago   
 7      The Farmers and Merchants State Bank of Argonia             Argonia   
 8                                  Fayette County Bank          Saint Elmo   
 9    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 10                                      First NBC Bank         New Orleans   
 11                                       Proficio B

## Json Data

In [22]:
import pandas as pd

data = pd.read_json('datajs.json')
print(data)

   ID      Name  Salary   StartDate        Dept
0   1      Rick  623.30    1/1/2012          IT
1   2       Dan  515.20   9/23/2013  Operations
2   3  Michelle  611.00  11/15/2014          IT
3   4      Ryan  729.00   5/11/2014          HR
4   5      Gary  843.25   3/27/2015     Finance
5   6      Nina  578.00   5/21/2013          IT
6   7     Simon  632.80   7/30/2013  Operations
7   8      Guru  722.50   6/17/2014     Finance


In [23]:
# Use the multi-axes indexing funtion
print (data.loc[[1,3,5],['Salary','Name']])

   Salary  Name
1   515.2   Dan
3   729.0  Ryan
5   578.0  Nina
